-- 코드를 입력하세요
WITH MILK_YOGURT AS (
    SELECT CART_ID, NAME
    FROM CART_PRODUCTS 
    WHERE NAME = 'Milk' OR NAME = 'Yogurt'
    GROUP BY CART_ID, NAME
)

SELECT CART_ID
FROM MILK_YOGURT
GROUP BY CART_ID
HAVING COUNT(*) = 2
ORDER BY 1