-- 코드를 입력하세요
WITH M AS (
    SELECT DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'MILK'
)
, Y AS (
    SELECT DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'YOGURT'
)

SELECT M.CART_ID
FROM M
    INNER JOIN Y
        ON M.CART_ID = Y.CART_ID
ORDER BY 1
