-- 코드를 작성해주세요
WITH FIRST_GEN AS
(
    SELECT ID
        , PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
SECOND_GEN AS
(
    SELECT A.ID
        , A.PARENT_ID
    FROM ECOLI_DATA AS A
        JOIN FIRST_GEN AS B
        ON B.ID = A.PARENT_ID
)

SELECT A.ID AS ID
FROM ECOLI_DATA AS A
        JOIN SECOND_GEN AS B
        ON B.ID = A.PARENT_ID
ORDER BY A.ID;