-- 코드를 작성해주세요
WITH CHILD AS (
    SELECT PARENT_ID
        , COUNT(*) AS COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY 1
)
SELECT A.ID
    , IF(B.COUNT IS NULL, 0, B.COUNT) AS CHILD_COUNT
FROM ECOLI_DATA A LEFT JOIN CHILD B ON A.ID = B.PARENT_ID
ORDER BY 1