-- 코드를 작성해주세요
SELECT B.ID
    , IFNULL(A.CHILD_COUNT, 0) AS CHILD_COUNT
FROM (SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT FROM ECOLI_DATA GROUP BY PARENT_ID) AS A
    RIGHT JOIN ECOLI_DATA B
        ON A.PARENT_ID = B.ID
ORDER BY 1