-- 코드를 입력하세요
WITH INFO AS(
    SELECT A.CAR_ID
        , A.CAR_TYPE
        , A.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR AS A
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
            ON A.CAR_ID = B.CAR_ID
    WHERE A.CAR_TYPE REGEXP 'SUV|세단'
        AND A.CAR_ID NOT IN (SELECT CAR_ID 
                            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                            WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
)

SELECT A.CAR_ID
    , A.CAR_TYPE
    , ROUND(A.DAILY_FEE * 30 * (100 - B.DISCOUNT_RATE) / 100) AS FEE
FROM INFO AS A
    INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS B
        ON A.CAR_TYPE = B.CAR_TYPE
WHERE B.DURATION_TYPE = '30일 이상'
    AND A.DAILY_FEE * 30 * ROUND((100 - B.DISCOUNT_RATE) / 100) >= 500000 
        AND A.DAILY_FEE * 30 * ROUND((100 - B.DISCOUNT_RATE) / 100) < 2000000
GROUP BY 1
ORDER BY 3 DESC, 2, 1 DESC