-- 코드를 작성해주세요
SELECT A.ID
    , CASE
        WHEN A.R >= 0.75 THEN 'CRITICAL' 
        WHEN A.R >= 0.5 THEN 'HIGH' 
        WHEN A.R >= 0.25 THEN 'MEDIUM' 
        ELSE 'LOW' 
      END AS COLONY_NAME
FROM (
    SELECT ID
        , PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) AS R
    FROM ECOLI_DATA 
) A
ORDER BY A.ID
