-- 코드를 입력하세요
SELECT YEAR(S.SALES_DATE) AS YEAR
    , MONTH(S.SALES_DATE) AS MONTH
    , U.GENDER
    , COUNT(DISTINCT U.USER_ID) AS USERS
FROM USER_INFO AS U
    JOIN ONLINE_SALE AS S
        ON U.USER_ID = S.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3