-- 코드를 입력하세요
WITH IS_RENTALED AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
)
SELECT DISTINCT(CAR_ID) AS CAR_ID
    , IF(CAR_ID IN (SELECT CAR_ID FROM IS_RENTALED), '대여중', '대여 가능') AS  AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY 1 DESC