-- 코드를 입력하세요
WITH ORDER_DATA AS
(
    SELECT PRODUCT_ID
        , SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE '2022-05-%'
    GROUP BY PRODUCT_ID
)


SELECT A.PRODUCT_ID
    , B.PRODUCT_NAME
    , A.AMOUNT * B.PRICE AS TOTAL_SALES
FROM ORDER_DATA A
    JOIN FOOD_PRODUCT B
        ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID

