-- 코드를 입력하세요
SELECT B.PRODUCT_ID
    , A.PRODUCT_NAME
    , (SUM(b.AMOUNT) * A.PRICE) TOTAL_SALES
FROM FOOD_PRODUCT AS A
    RIGHT JOIN FOOD_ORDER AS B
        ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE B.PRODUCE_DATE LIKE '2022-05%'
    AND A.PRODUCT_ID IS NOT NULL
GROUP BY 1
ORDER BY 3 DESC, 1