-- 코드를 작성해주세요
SELECT DISTINCT ID
    , EMAIL
    , FIRST_NAME
    , LAST_NAME
FROM DEVELOPERS AS A
    JOIN SKILLCODES AS B
        ON A.SKILL_CODE & B.CODE = B.CODE
WHERE CATEGORY = 'Front End'
ORDER BY 1