-- 코드를 입력하세요
SELECT A.WRITER_ID,
    B.NICKNAME,
    SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS A
    JOIN USED_GOODS_USER AS B
        ON A.WRITER_ID = B.USER_ID
WHERE STATUS = 'DONE'
    AND WRITER_ID IN (SELECT WRITER_ID
                     FROM USED_GOODS_BOARD 
                     WHERE STATUS = 'DONE'
                     GROUP BY WRITER_ID
                     HAVING SUM(PRICE) >= 700000)
GROUP BY 1, 2
ORDER BY 3
