-- 코드를 작성해주세요
SELECT A.EMP_NO
    , A.EMP_NAME
    , CASE
        WHEN AVG(C.SCORE) >= 96 THEN 'S'
        WHEN AVG(C.SCORE) >= 90 THEN 'A'
        WHEN AVG(C.SCORE) >= 80 THEN 'B'
        ELSE 'C'
      END GRADE
    , CASE
        WHEN AVG(C.SCORE) >= 96 THEN SAL * 0.2
        WHEN AVG(C.SCORE) >= 90 THEN SAL * 0.15
        WHEN AVG(C.SCORE) >= 80 THEN SAL * 0.1
        ELSE 0
      END BONUS
FROM HR_EMPLOYEES A
    JOIN HR_DEPARTMENT B
        ON A.DEPT_ID = B.DEPT_ID
    JOIN HR_GRADE C
        ON A.EMP_NO = C.EMP_NO
GROUP BY A.EMP_NO
ORDER BY 1
