-- 코드를 입력하세요
WITH REVIEW_DATA AS
(
    SELECT MEMBER_ID
        , DENSE_RANK() OVER (ORDER BY COUNT(MEMBER_ID) DESC) AS REVIEW_RANK
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
)


SELECT MEMBER_NAME
    , REVIEW_TEXT
    , DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS A
    JOIN REST_REVIEW  AS B
        USING (MEMBER_ID)
WHERE MEMBER_ID IN 
                (
                    SELECT MEMBER_ID
                    FROM REVIEW_DATA
                    WHERE REVIEW_RANK = 1
                )
ORDER BY REVIEW_DATE, REVIEW_TEXT