-- 코드를 작성해주세요
WITH MAX_INFO AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR
        , MAX(SIZE_OF_COLONY) AS MAX_VALUE
    FROM ECOLI_DATA 
    GROUP BY 1
)

SELECT A.YEAR AS YEAR
    , A.MAX_VALUE - B.SIZE_OF_COLONY AS YEAR_DEV
    , B.ID AS ID
FROM MAX_INFO AS A
    JOIN ECOLI_DATA AS B
        ON A.YEAR = YEAR(B.DIFFERENTIATION_DATE)
ORDER BY 1, 2
