-- 코드를 작성해주세요
WITH MAX_SIZE AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR
        , MAX(SIZE_OF_COLONY) AS SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(A.DIFFERENTIATION_DATE) YEAR
    , (B.SIZE - A.SIZE_OF_COLONY) YEAR_DEV
    , A.ID
FROM ECOLI_DATA A
    JOIN MAX_SIZE B
        ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY 1, 2