-- 코드를 작성해주세요
SELECT SUM(C.SCORE) SCORE 
    , C.EMP_NO
    , B.EMP_NAME
    , B.POSITION
    , B.EMAIL
FROM HR_EMPLOYEES B
    JOIN HR_GRADE C
        ON B.EMP_NO = C.EMP_NO
GROUP BY 2
HAVING SUM(C.SCORE) = (SELECT SUM(SCORE) FROM HR_GRADE WHERE YEAR = '2022' GROUP BY EMP_NO ORDER BY 1 DESC LIMIT 1)
