-- 코드를 작성해주세요
SELECT SUM(B.SCORE) AS SCORE
    , B.EMP_NO
    , A.EMP_NAME
    , A.POSITION
    , A.EMAIL
FROM HR_EMPLOYEES A
    JOIN HR_GRADE B
        ON A.EMP_NO = B.EMP_NO
WHERE B.YEAR = '2022'
GROUP BY B.EMP_NO
ORDER BY 1 DESC
LIMIT 1



