-- 코드를 입력하세요
SELECT '/home/grep/src/' || A.BOARD_ID || '/' || A.FILE_ID || A.FILE_NAME || A.FILE_EXT AS FILE_PATH
FROM USED_GOODS_FILE A
JOIN (
    SELECT BOARD_ID
    FROM (
        SELECT BOARD_ID
        FROM USED_GOODS_BOARD 
        ORDER BY VIEWS DESC
    )
    WHERE ROWNUM = 1
) B
ON A.BOARD_ID = B.BOARD_ID
ORDER BY FILE_PATH DESC