-- 코드를 작성해주세요
SELECT COUNT(*) FISH_COUNT
    , MAX(LENGTH) MAX_LENGTH
    , FISH_TYPE
FROM FISH_INFO 
GROUP BY 3
HAVING AVG(CASE
            WHEN LENGTH >10 THEN LENGTH
            ELSE 10
           END) >= 33
ORDER BY 3